version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install a modern HTML linting tool
      - echo "Installing HTMLHint..."
      - npm install -g htmlhint
  pre_build:
    commands:
      # Run the HTMLHint tool to "test" our HTML file
      - echo "Running HTMLHint test..."
      - htmlhint **/*.html
  build:
    commands:
      - echo "Build phase started on `date`"
      - echo "No build actions needed for this simple site."

artifacts:
  # Tell CodeBuild which files to pass to the next stage (S3 Deploy)
  files:
    - '**/*'